<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Connection360.Domain\Connection360.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Enum\" />
  </ItemGroup>

</Project>
