<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.0.0-alphaBaseInit.1</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<AssemblyFileVersion>1.0.0.0</AssemblyFileVersion>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Auth0.ManagementApi" Version="10.0.0" />
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
		<PackageReference Include="Npgsql" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Connection360.Application\Connection360.Application.csproj" />
		<ProjectReference Include="..\Connection360.Domain\Connection360.Domain.csproj" />
	</ItemGroup>

</Project>
