<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Connection360.ApiGateway</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
		<!-- YARP: reverse proxy / enrutamiento hacia los microservicios internos -->
		<PackageReference Include="Yarp.ReverseProxy" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
		<!-- Rate limiting usa System.Threading.RateLimiting, incluido nativamente en el SDK Web de ASP.NET Core >= 7 -->
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Connection360.Application\Connection360.Application.csproj" />
	</ItemGroup>

</Project>
